language: cpp

compiler: clang

before_install:
 - echo 'yes' | sudo add-apt-repository ppa:mapnik/boost
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev libboost-system-dev libboost-thread-dev python-nose libicu-dev libpng-dev libjpeg-dev libtiff-dev libz-dev libfreetype6-dev libxml2-dev libproj-dev

script:
 - ./configure DEMO=False BINDINGS='' CPP_TESTS=False CAIRO=False INPUT_PLUGINS='' OPTIMIZATION=1 JOBS=2 FAST=True && make

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.org#mapnik"
    use_notice: true
